version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=local
      - POSTGRES_USER=luiz
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - ../postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    depends_on:
      - postgres
